version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:latest  # Use a Docker image suitable for your project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

  sonar_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Docker image for SonarQube scanner
    steps:
      - checkout
      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey="YOUR_PROJECT_KEY" \
              -Dsonar.sources="." \
              -Dsonar.host.url="YOUR_SONARQUBE_SERVER_URL" \
              -Dsonar.login="${SONAR_TOKEN}"

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
      - sonar_scan:
          requires:
            - build
